version: '3'

services:
  db:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=store
    ports:
      - "3307:3306"
  redstoreapi:
    image: redstoreapi
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/store?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    build:
      context: "../redstoreapi"
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always